/**
 * PetRadar.Web.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const AppointmentTypeEnum = {
    Checkup: 'Checkup',
    Vaccination: 'Vaccination',
    Surgery: 'Surgery',
    Grooming: 'Grooming',
    Consultation: 'Consultation',
    Other: 'Other'
} as const;
export type AppointmentTypeEnum = typeof AppointmentTypeEnum[keyof typeof AppointmentTypeEnum];

