/**
 * PetRadar.Web.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Coordinate } from './coordinate';
import { Ordinates } from './ordinates';


export interface CoordinateSequence { 
    readonly dimension?: number;
    readonly measures?: number;
    readonly spatial?: number;
    ordinates?: Ordinates;
    readonly hasZ?: boolean;
    readonly hasM?: boolean;
    readonly zOrdinateIndex?: number;
    readonly mOrdinateIndex?: number;
    first?: Coordinate;
    last?: Coordinate;
    readonly count?: number;
}
export namespace CoordinateSequence {
}


