/**
 * PetRadar.Web.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Coordinate } from './coordinate';


export interface Envelope { 
    readonly isNull?: boolean;
    readonly width?: number;
    readonly height?: number;
    readonly diameter?: number;
    readonly minX?: number;
    readonly maxX?: number;
    readonly minY?: number;
    readonly maxY?: number;
    readonly area?: number;
    readonly minExtent?: number;
    readonly maxExtent?: number;
    centre?: Coordinate;
}

