/**
 * PetRadar.Web.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GeometryFactory } from './geometryFactory';
import { Coordinate } from './coordinate';
import { PrecisionModel } from './precisionModel';
import { Dimension } from './dimension';
import { Point } from './point';
import { Envelope } from './envelope';
import { OgcGeometryType } from './ogcGeometryType';


export interface Geometry { 
    factory?: GeometryFactory;
    userData?: any | null;
    srid?: number;
    readonly geometryType?: string | null;
    ogcGeometryType?: OgcGeometryType;
    precisionModel?: PrecisionModel;
    coordinate?: Coordinate;
    readonly coordinates?: Array<Coordinate> | null;
    readonly numPoints?: number;
    readonly numGeometries?: number;
    readonly isSimple?: boolean;
    readonly isValid?: boolean;
    readonly isEmpty?: boolean;
    readonly area?: number;
    readonly length?: number;
    centroid?: Point;
    interiorPoint?: Point;
    pointOnSurface?: Point;
    dimension?: Dimension;
    boundary?: Geometry;
    boundaryDimension?: Dimension;
    envelope?: Geometry;
    envelopeInternal?: Envelope;
    readonly isRectangle?: boolean;
}
export namespace Geometry {
}


