/**
 * PetRadar.Web.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoordinateSequenceFactory } from './coordinateSequenceFactory';
import { PrecisionModel } from './precisionModel';


export interface NtsGeometryServices { 
    geometryOverlay?: object;
    coordinateEqualityComparer?: object;
    readonly defaultSRID?: number;
    defaultCoordinateSequenceFactory?: CoordinateSequenceFactory;
    defaultPrecisionModel?: PrecisionModel;
}

