/**
 * PetRadar.Web.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PetSpeciesEnum = {
    Dog: 'Dog',
    Cat: 'Cat'
} as const;
export type PetSpeciesEnum = typeof PetSpeciesEnum[keyof typeof PetSpeciesEnum];

