/**
 * PetRadar.Web.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const PetSizeEnum = {
    Small: 'Small',
    Medium: 'Medium',
    Large: 'Large'
} as const;
export type PetSizeEnum = typeof PetSizeEnum[keyof typeof PetSizeEnum];

