/**
 * PetRadar.Web.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoordinateSequence } from './coordinateSequence';
import { Geometry } from './geometry';
import { GeometryFactory } from './geometryFactory';
import { Coordinate } from './coordinate';
import { PrecisionModel } from './precisionModel';
import { Dimension } from './dimension';
import { Envelope } from './envelope';
import { OgcGeometryType } from './ogcGeometryType';


export interface Point { 
    factory?: GeometryFactory;
    userData?: any | null;
    srid?: number;
    precisionModel?: PrecisionModel;
    readonly numGeometries?: number;
    readonly isSimple?: boolean;
    readonly isValid?: boolean;
    readonly area?: number;
    readonly length?: number;
    centroid?: Point;
    interiorPoint?: Point;
    pointOnSurface?: Point;
    envelope?: Geometry;
    envelopeInternal?: Envelope;
    readonly isRectangle?: boolean;
    coordinateSequence?: CoordinateSequence;
    readonly coordinates?: Array<Coordinate> | null;
    readonly numPoints?: number;
    readonly isEmpty?: boolean;
    dimension?: Dimension;
    boundaryDimension?: Dimension;
    x?: number;
    y?: number;
    coordinate?: Coordinate;
    readonly geometryType?: string | null;
    ogcGeometryType?: OgcGeometryType;
    boundary?: Geometry;
    z?: number;
    m?: number;
}
export namespace Point {
}


