/**
 * PetRadar.Web.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrecisionModels } from './precisionModels';


export interface PrecisionModel { 
    readonly isFloating?: boolean;
    readonly maximumSignificantDigits?: number;
    scale?: number;
    readonly gridSize?: number;
    precisionModelType?: PrecisionModels;
}
export namespace PrecisionModel {
}


