/**
 * PetRadar.Web.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const RoleEnum = {
    SuperAdmin: 'SuperAdmin',
    Admin: 'Admin',
    User: 'User',
    Organization: 'Organization',
    NotSet: 'NotSet'
} as const;
export type RoleEnum = typeof RoleEnum[keyof typeof RoleEnum];

