/**
 * PetRadar.Web.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserTokenViewModel { 
    token?: string | null;
    tokenValidTo?: string;
    refreshToken?: string | null;
    refreshTokenExpiryTime?: string;
}

