/**
 * PetRadar.Web.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AppointmentTypeEnum } from './appointmentTypeEnum';
import { Point } from './point';
import { AppointmentStatusEnum } from './appointmentStatusEnum';


export interface VeterinaryAppointmentUpdateModel { 
    veterinaryName?: string | null;
    appointmentType?: AppointmentTypeEnum;
    appointmentStatus?: AppointmentStatusEnum;
    appointmentDate?: string | null;
    durationInMinutes?: number | null;
    reasonForVisit?: string | null;
    notes?: string | null;
    diagnosis?: string | null;
    treatment?: string | null;
    prescriptions?: string | null;
    location?: Point;
    cost?: number | null;
    addressText?: string | null;
}
export namespace VeterinaryAppointmentUpdateModel {
}


