/**
 * PetRadar.Web.API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VeterinaryAppointmentViewModel { 
    id?: number;
    petId?: number;
    veterinaryName?: string | null;
    appointmentType?: string | null;
    appointmentStatus?: string | null;
    appointmentDate?: string;
    durationInMinutes?: number | null;
    reasonForVisit?: string | null;
    notes?: string | null;
    diagnosis?: string | null;
    treatment?: string | null;
    prescriptions?: string | null;
    cost?: number | null;
    addressText?: string | null;
    reminderSent?: boolean;
}

